name: CI

on:
  pull_request:
    branches:
      - user
    types:
      - opened
  push:
    branches:
      - main

jobs:
  merge-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Merge pull request to main
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: repo-sync/pull-request@v3
        with:
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          method: merge
